version: '3'

services:
  app:
    build: .
    entrypoint: ./.docker/entrypoint.sh
    container_name: dongo-api
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app

  db:
    build: .docker/postgres
    restart: always
    tty: true
    volumes:
      - .docker/dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    depends_on:
      - app

  pgadmin:
    image: dpage/pgadmin4
    tty: true
    environment:
      - PGADMIN_DEFAULT_EMAIL=${DB_USER_MAIL}
      - PGADMIN_DEFAULT_PASSWORD=${DB_USER_PASSWORD}
    ports:
      - '9000:80'
    depends_on:
      - db
