name: Stress test
  
on:
  push:
    branches:
      - master

jobs:
  run-server:
    name: Run server and stress test with k6
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: root
          POSTGRES_DB: dongo_api
        ports:
        - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: 14.x
      - name: Install k6
        run: |
          curl https://github.com/loadimpact/k6/releases/download/v0.28.0/k6-v0.28.0-linux64.tar.gz -L | tar xvz --strip-components 1
      - uses: bahmutov/npm-install@v1
      - name: Setup the project
        run: |
          npm install
          npm run build
          npm run env
          npm run typeorm migration:run
        env:
          DATABASE_URL: postgres://postgres:root@localhost:${{ job.services.postgres.ports[5432] }}/dongo_api
      - name: Run the server
        run: npm run start:dev &
        env:
          PORT: 3000          
          DATABASE_URL: postgres://postgres:root@localhost:${{ job.services.postgres.ports[5432] }}/dongo_api
          ALLOWED_ORIGINS: 'http://localhost:3000'
      - name: Run k6 local test
        run: ./k6 run stress-test/main.js